/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GiaoDien;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Loi
 */
public class frmMenu extends javax.swing.JFrame {

    public static boolean isOpenFrmChuyenMuc = false;
    public static boolean isOpenFrmLop = false;
    public static boolean isOpenFrmPhieuMuonSach = false;
    public static boolean isOpenFrmPhieuTraSach1 = false;
    public static boolean isOpenFrmSinhVien = false;
    public static boolean isOpenFrmTraCuuPhieuMuon = false;
    public static boolean isOpenFrmSach = false;

    public frmMenu() {
        initComponents();
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        ChuyenMuc = new javax.swing.JMenuItem();
        Sach = new javax.swing.JMenuItem();
        SinhVien = new javax.swing.JMenuItem();
        Lop = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        LapPhieuMuon = new javax.swing.JMenuItem();
        LapPhieuTra = new javax.swing.JMenuItem();
        Menu4 = new javax.swing.JMenu();
        frmMuonTra = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        jMenu1.setText("Hệ Thống");
        jMenu1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jMenuItem1.setText("Kết Thúc");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Danh Mục");
        jMenu2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        ChuyenMuc.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        ChuyenMuc.setText("Chuyên Mục");
        ChuyenMuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChuyenMucActionPerformed(evt);
            }
        });
        jMenu2.add(ChuyenMuc);

        Sach.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        Sach.setText("Sách");
        Sach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SachActionPerformed(evt);
            }
        });
        jMenu2.add(Sach);

        SinhVien.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        SinhVien.setText("Sinh Viên");
        SinhVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SinhVienActionPerformed(evt);
            }
        });
        jMenu2.add(SinhVien);

        Lop.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        Lop.setText("Lớp");
        Lop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LopActionPerformed(evt);
            }
        });
        jMenu2.add(Lop);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Quản lý phiếu");
        jMenu3.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        LapPhieuMuon.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        LapPhieuMuon.setText("Lập phiếu mượn");
        LapPhieuMuon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LapPhieuMuonActionPerformed(evt);
            }
        });
        jMenu3.add(LapPhieuMuon);

        LapPhieuTra.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        LapPhieuTra.setText("Lập phiếu trả");
        LapPhieuTra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LapPhieuTraActionPerformed(evt);
            }
        });
        jMenu3.add(LapPhieuTra);

        jMenuBar1.add(jMenu3);

        Menu4.setText("Tra cứu");
        Menu4.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        frmMuonTra.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        frmMuonTra.setText("Mượn trả");
        frmMuonTra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frmMuonTraActionPerformed(evt);
            }
        });
        Menu4.add(frmMuonTra);

        jMenuBar1.add(Menu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 691, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 517, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void SachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SachActionPerformed
        if (isOpenFrmSach == false) {
            new frmSach().setVisible(true);
            isOpenFrmSach = true;
        } else {
            JOptionPane.showMessageDialog(this, "Mục này đang được mở !");
        }
    }//GEN-LAST:event_SachActionPerformed

    private void SinhVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SinhVienActionPerformed
        if (isOpenFrmSinhVien == false) {
            new frmSinhVien().setVisible(true);
            isOpenFrmSinhVien = true;
        } else {
            JOptionPane.showMessageDialog(this, "Mục này đang được mở !");
        }
    }//GEN-LAST:event_SinhVienActionPerformed

    private void ChuyenMucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChuyenMucActionPerformed
        if (isOpenFrmChuyenMuc == false) {
            new frmChuyenMuc().setVisible(true);
            isOpenFrmChuyenMuc = true;
        } else {
            JOptionPane.showMessageDialog(this, "Mục này đang được mở !");
        }
    }//GEN-LAST:event_ChuyenMucActionPerformed

    private void LopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LopActionPerformed

        if (isOpenFrmLop == false) {
            new frmLop().setVisible(true);
            isOpenFrmLop = true;
        } else {
            JOptionPane.showMessageDialog(this, "Mục này đang được mở !");
        }
    }//GEN-LAST:event_LopActionPerformed

    private void LapPhieuMuonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LapPhieuMuonActionPerformed
        try {
            if (isOpenFrmPhieuMuonSach == false) {
                new frmPhieuMuonSach().setVisible(true);
                isOpenFrmPhieuMuonSach = true;
            } else {
                JOptionPane.showMessageDialog(this, "Mục này đang được mở !");
            }
        } catch (IOException ex) {
            Logger.getLogger(frmMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_LapPhieuMuonActionPerformed

    private void LapPhieuTraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LapPhieuTraActionPerformed
        if (isOpenFrmPhieuTraSach1 == false) {
            new frmPhieuTraSach1().setVisible(true);
            isOpenFrmPhieuTraSach1 = true;
        } else {
            JOptionPane.showMessageDialog(this, "Mục này đang được mở !");
        }
    }//GEN-LAST:event_LapPhieuTraActionPerformed

    private void frmMuonTraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frmMuonTraActionPerformed

        try {
            if (isOpenFrmTraCuuPhieuMuon == false) {
                new frmTraCuuPhieuMuon().setVisible(true);
                isOpenFrmTraCuuPhieuMuon = true;
            } else {
                JOptionPane.showMessageDialog(this, "Mục này đang được mở !");
            }
        } catch (IOException ex) {
            Logger.getLogger(frmMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_frmMuonTraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ChuyenMuc;
    private javax.swing.JMenuItem LapPhieuMuon;
    private javax.swing.JMenuItem LapPhieuTra;
    private javax.swing.JMenuItem Lop;
    private javax.swing.JMenu Menu4;
    private javax.swing.JMenuItem Sach;
    private javax.swing.JMenuItem SinhVien;
    private javax.swing.JMenuItem frmMuonTra;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
